# CI build definition for https://ci.appveyor.com/project/olegsych/simply-clr-metadata
# To learn more, see http://www.appveyor.com/docs/appveyor-yml

version: 0.1.{build}

pull_requests:
  do_not_increment_build_number: true

branches:
  only:
  - master

skip_tags: true

os: Visual Studio 2015

build_script:
- set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
- nuget restore
- msbuild simply.clr.metadata.sln /m /p:Platform=x86 /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
- msbuild simply.clr.metadata.sln /m /p:Platform=x64 /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

test_script:
- vstest.console bin\debug\Win32\test.dll /Platform:x86 /logger:Appveyor
- vstest.console bin\debug\x64\test.dll /Platform:x64 /logger:Appveyor /inIsolation
